[package]
name = "server-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "*"
serde = { version = "1", features = ["derive"] }
crossbeam-channel = "*"
ctrlc = "3.4.4"
system_shutdown = "4"
